type Query {
  events: [Event],
  event(eventId: Int!): Event
}

type Event {
  eventId: Int,
  eventDate: Date,
  eventTime: Time,
  subCategory: SubCategory,
  type: String,
  linkAddress: String,
  user: User,

  organizatorEntityType: String,
  organizatorLegalName: String,
  organizatorProfession: String,
  organizatorPhone: String,
  organizatorAdditionalPhone: String,

  postTitle: String,
  postDescription: String,
  postImages: [String],
  postText: String
}

type Mutation {
  addEvent(eventDate: Date!, eventTime: Time!, subCategoryId: Int!, type: String!, linkAddress: String!, organizatorEntityType: String!, organizatorLegalName: String, organizatorProfession: String!, organizatorPhone: String!, organizatorAdditionalPhone: String, postTitle: String!, postDescription: String!, postImages: [String], postText: String!): Response!,
  deleteEvent(eventId: Int!): Response!
}
