type Response {
  status: Int
  message: String
  data: Any
}

type RegisterAndLoginResponse {
  status: Int
  message: String
  token: String
  data: User
}

scalar Any
scalar Date
scalar Time
scalar DateTime
